sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.3.0
  - jruby
env:
  - JRUBY_OPTS=-X-C
before_install: gem install bundler -v 1.12.5
addons:
    code_climate:
        repo_token: 187c1770b00f655d852f632d3a491518c30fd3923674057bbbd03c2d8efb7503
